apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: capacitor
spec:
  parentRefs:
    - name: platform-private
      namespace: infrastructure
  hostnames:
    - "capacitor-local.priv.arcksystem.local"
  rules:
    - backendRefs:
        - name: capacitor
          port: 9000
