apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:WjyPsGpFHlPaA4CuAU7wTHpqU8sIgmq2mc5LlpA62lROskaph7Zp5VSUTBZVQ4OQ1vQ/rkCP1XJIKhSdtk/8HB59bfLjf89riUhP6cH+PH4MO1+RFfp4QoZwjlvN3A==,iv:zFsxmZcQs+p+j3YhPaWy3W/xdbWah7jjjAthPAEc+d8=,tag:BPZPX1sm3OQffoL2YkfUCQ==,type:str]
    TEST_ADD: ENC[AES256_GCM,data:gXU5jg==,iv:yCsDCrRDOn2YXMCZ3UNrzyDd23OCbuFRB8+EuEVcf9I=,tag:fgAub0uxQrwBlYJ0iZ5DDA==,type:str]
    LB_RANGE: ENC[AES256_GCM,data:qUrf0mmJtA4w8mCpQjNZxRnAafA5J+kx4Nqu,iv:t+O5WN8xOnG5OnUFZU/VoCKdx7QORpglrQRIUPO7sAA=,tag:CU7mMcnNXc72V6CBn+BstA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpngrq45glezcyxdqf00l756yn9xhrayg9mvt0r4eupq6l5ygdsf2qlw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWUFjdWtXN3ZTVHhuQVYr
            NHh6azlWVGJGdlpuNi9mM1FPQzRzNlpraGpFClhiSDF5Y1Q5aFFjNUF1a1ZqNnJR
            WGZrd0JpQ200N2REbDVMbE40Rm4rSjQKLS0tIE5Fa1F0UFFONmgvTEVDWjZxM2c4
            NkpvTGczSnlFbngxRTVvTVY3RjRjcnMKW0OYxmg1klu7p861fyyAeIEJUZf7LKGL
            Oe52/jljMA0r4xEG/xgrd97doTfKWlQFHhYOU/IyWYzkeTaxgddrvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-29T15:35:02Z"
    mac: ENC[AES256_GCM,data:wwTvZjLAsVdMm/PEYUA0aXkQ+Gdvb0VsSoRGL3Pz3z9ID86GnZ/nmWvzyK8x2nJYTtmWzh0bH3XXIYOuJ5WctQFSTiCh4GtrMdGZOui6hs6HI5moK0MDiEXY22mgQblzhH/YNVDb4Fp7FwAYnCTekuEDUFv26BJHw/Gt6CYHvao=,iv:ctP4n6doJ8rXI95DNOrk+NOz5BLne/m3MjHf93jI8N0=,tag:vsujtBeYaVpWWRCRIgRTmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
