apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:agtDwOeFS7YzHiPtvmNMyYLNS4JcSOb/fgVl3BW6GUeK9HIeZxthoTIa1EfhD7Q9RhVP/1vMC0OPChbUr6l0VNoXWSx+be/DnOMy7krMx+IvwRHPQmj64N8d9YysJA==,iv:++Vp3VNjW6owZZ9OpHF1/4J6QtqQdYuCrzjd5uHoPs0=,tag:1JY6WhJusKHYpV4eHWLYBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-24T15:57:26Z"
    mac: ENC[AES256_GCM,data:NOHMsdASuJeYEQWyGhl2WqOv89QpvF8OJsZpvFz/hecsj5gKLbI5g82rbdxtlIvgiu4lpG1flGgIla6CRJkPlK34ZiAnsrm34UwZ9eqdAKPKdy5C6xANJgWQ03dh01hAUXgopdSCbXcDy8IWVraH8qb/JH0+CseAUHGZJhr+uwk=,iv:pZYnbVfb7htdbtbQfhC4ISomDIg52NStzcHNNHJgxhM=,tag:aJ7JARdzxiJ+zThgT9wJ2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
