apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:owYjUF5Hmj+dWyeOB7AeJFTD1rKeSCHTw/zeChYMVpM=,iv:Y3krjCNdCbQ4YwrWqucCEOTQxhTsXYxksDG25vElv1Y=,tag:2jOjkIA2n/UMQpkxY6oKvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-24T15:57:26Z"
    mac: ENC[AES256_GCM,data:Zzn1rkj3KfTnhquTAaOBaGoQSgPmbtAKp8nSv7aSBb17zW+Fw8IFQk7LJ0OTxydwbBBku64fefCg5Y6Kv18hjgYR4fP2eug5PCD7L6KWOv6345mW6MmxLhnQMrECOZGvEJB7B1N8wv6GovPL1vUkiBi+lQP1YIkInVOuDv2phmw=,iv:JW1bNWDw65NaFs0pfxOTfzy+vVvi+mCo5Dd1dOcgdkU=,tag:SJSmcQwAhi78lWNwk/7Dcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
